services:

  mysql:
    image: mysql:8.0 # Imagen oficial de MySQL 8
    container_name: mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQLDB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASS}
    ports:
      - "${MYSQLDB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Asocia volumen para persistencia de datos (los datos persisten aunque se borre el contenedor)

  ssdd_taller:
    build: ./
    container_name: ssdd_taller
    restart: always
    env_file:
      - ./.env
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: # Volumen nombrado para almacenar datos de MySQL